chainlink-functions/README.md
chainlink-functions/example/request.js
chainlink-functions/example/source.js

Code is added to retrieve access token for spaceandtime

feat: add code to retrieve sxt access token

---

.github/workflows/preview-release.yml
.github/workflows/release.yml

This repository currently does not have conventional changelog actions built in.
SxT has standardized on conventional changelog actions so that semver bumping is automatic and github releases are created with every merge. The workflows added here meet this standard.
- preview-release workflow added
- release workflow added
No. These tests do not affect existing functionality.

ci: create releases on merges to main and preview releases in PRs

---

.github/workflows/preview-release.yml
.github/workflows/release.yml

Currently, the release workflows attempt to pull github authentication from 1password. However, this workflow is only intended for use in non-public SxT workflows. Since we do not need access to private SxT information to perform these releases, using the secret github token should suffice for now.
Steps that attempt to use custom github authentication are removed or now use `secrets.GH_TOKEN`.
No. These changes do not affect existing functionality.

ci: authenticate with default github token in release workflows

---

.github/workflows/release.yml
node/src/build_index.sh
node/src/index_tail.js
rust-toolchain.toml

A javascript port of the rust sdk client is convenient for use in javascript environments like chainlink. This adds such a port in index_tail.js, which can be attached to the index.js produced by wasm-pack using the provided build_index.sh script. It also adds steps to the release CI for adding the resulting build as a release artifact in this repository.
- feat: add javascript client and script to attach it to wasm-pack
- feat: set rust toolchain channel to 1.81
- ci: build wasm and javascript index as artifacts of release
We have done testing with chainlink using this build process, just not within the CI. The CI release process will only be tested by merging this.

feat: add javascript client and build it into release CI

---

.github/workflows/release.yml

For the greatest user experience in chainlink functions and javascript in general, the javascript port of the sdk client should be accessible in NPM. This adds various steps to the release CI to enable this automation.
Depends on #41 
Steps added to release CI to manage package.json and publish to npm.
No, they will only be tested by merging this PR unfortunately.

ci: publish node directory as npm package in release CI

---

crates/proof-of-sql-sdk/examples/cli/args.rs
crates/proof-of-sql-sdk/examples/cli/main.rs
crates/proof-of-sql-sdk/examples/count-ethereum-core/main.rs
crates/proof-of-sql-sdk/src/client.rs
crates/proof-of-sql-sdk/src/substrate.rs
node/src/index_tail.js

Currently, both the rust and javascript clients perform queries at the latest block. We want to be able to perform queries at older blocks too. This is especially important for the chainlink use case, as chainlink's DON will perform the same query multiple times, expecting the same results from each run. To this end, this changes both clients and their underlying functions to accept an optional block hash.
- rust client updated to accept an optional block ref with queries
- rust CLI updated to accept an optional block hash
- javascript client updated to accept an optional block hash
Only localy, no automated tests as these are difficult with the current stateful structure of the affected code.

feat: support querying at particular blocks

---

node/src/index_tail.js

A difference between the behavior of the rust and javascript clients has been observed which leads to StaleTableData errors in the javascript. When no particular block was requested, the javascript client was simply using the jsonrpc getStorage method without supplying a block. In this case, the jsonrpc uses the latest block, which is not necessarily finalized. On the other hand, the rust was implicitly requesting the latest finalized block via subxt. This change makes it so the javascript is only requesting finalized blocks too, which is important since only events in finalized blocks are inserted to the database.
- getFinalizedHead method added to javascript client
- if blockHash is null, the finalized head is requested
No.

fix: only query finalized blocks in javascript client

---

Cargo.lock
Cargo.toml

Proof-of-sql 0.73.1 is the version that we are syncing SxT chain and the prover service to. To avoid any potential compatibility issues, the SDK should be upgraded in sync as well.
proof-of-sql dependencies updated to 0.73.1
These changes do not affect functionality, which is verified by existing tests.

feat!: upgrade proof-of-sql to 0.73.1

---

Cargo.lock
Cargo.toml
crates/proof-of-sql-sdk-local/Cargo.toml
crates/proof-of-sql-sdk-local/src/prover_query.rs
crates/proof-of-sql-sdk-local/src/verify.rs

Recently, proof-of-sql and its dependent services have begun using bincode with fixed-int encoding and big-endian for serializing/deserializing over the network. This is because this format is fairly small and fairly EVM friendly.
This change makes it so ProofPlans are serialized w/ bincode and VerifiableQueryResults are deserialized w/ bincode accordingly.
No. This repository needs more test coverage in general, but this is not the PR to add it.

fix: use bincode for de/serializing proof-of-sql objects

---

.github/workflows/lint-and-test.yml

In previous versions of rustup, the active toolchain (defined by rust-toolchain.toml) would automatically be installed by cargo. Now, this needs to be performed as a separate command. This change copes with the breaking rustup behavior in CI.
- Install active rustup toolchain as separate command in CI
No, these changes do not affect functionality.

fix: install active toolchain in CI after rustup 1.28 upgrade

---

Cargo.lock
Cargo.toml

proof-of-sql 0.73.1 was unexpectedly limited in its VarBinary support. In particular, it did not implement arrow conversions for the VarBinary column type. These conversions have since been added and released in proof-of-sql.
This may not be strictly necessary for the SDK, but it is an easy update to make, and will ensure that the proof-of-sql version is in sync between the SDK and the prover service.
- proof-of-sql is upgraded to 0.75.2
These changes should not affect existing functionality.

fix: upgrade to proof-of-sql 0.75.2

---

crates/proof-of-sql-sdk-local/src/prover_query.rs
crates/proof-of-sql-sdk/src/client.rs

Proof-of-sql has been gradually switching to sqlparser for its parsing and sql typing. One consequence of this change is that TableRefs are no longer case insensitive. Previously, constructing TableRefs would coerce the identifier to lowercase. To preserve previous behavior, this now needs to be done manually.
TableRefs are converted to lowercase at the start of the client code.
No. This repository does not have great test coverage in general, but this is not the PR to add it.

fix: coerce input table refs to lowercase

---

rust-toolchain.toml

Following PoSQL we are bumping Rust to 1.85.0
See above
N/A.

feat: bump Rust to 1.85.0

---

Cargo.lock
Cargo.toml

Proof-of-sql has recently received improved VarBinary column support. In particular, it now supports equality and parsing literals. This change pulls these features into the SDK so that it can create ProvableAsts and perform verification accordingly.
Proof-of-sql dependencies have been upgraded to 0.76.11
No. This repository needs greater test coverage in general, but this is not the PR to add it.

feat: upgrade proof-of-sql to 0.76.11

---

README.md

- add reference to SxT API key in `README.md`
- add installation requirements

docs: add reference to SxT API key in `README.md`

---

Cargo.lock
Cargo.toml
crates/proof-of-sql-sdk-local/Cargo.toml
crates/proof-of-sql-sdk-local/build.rs
crates/proof-of-sql-sdk-local/proto/prover.proto
crates/proof-of-sql-sdk-local/src/duration_serde.rs
crates/proof-of-sql-sdk-local/src/lib.rs
crates/proof-of-sql-sdk-local/src/verify.rs

We need to make sure proto files across Proof of SQL remain in sync. Hence I updated the proto files and fixed the code to align with the new ones.

feat: update proto files and bump `proof-of-sql` to 0.86.0

---

crates/proof-of-sql-sdk-local/src/sxt_chain_runtime.rs
crates/proof-of-sql-sdk/src/substrate.rs

We get `Metadata(IncompatibleCodegen)` when running the SDK so we need to regenerate the runtime

feat: regenerate sxt chain runtime

---

crates/proof-of-sql-sdk-local/src/prover_query.rs
crates/proof-of-sql-sdk/src/client.rs

It seems that QueryExpr::try_new is probably coercing the table refs and column refs to lowercase. This is an issue for using the query commitments provided by substrate as a SchemaAccessor, as all of substrate's table identifiers and column identifiers are coerced to uppercase.
This PR attempts to work around the issue by implementing a SchemaAccessor that coerces to uppercase before querying an inner SchemaAccessor.

fix: workaround difference in casing between QueryExpr and storage

---

Cargo.lock
README.md
crates/proof-of-sql-sdk-local/src/prover_query.rs
crates/proof-of-sql-sdk/Cargo.toml
crates/proof-of-sql-sdk/examples/cli/args.rs
crates/proof-of-sql-sdk/examples/cli/main.rs
crates/proof-of-sql-sdk/examples/count-ethereum-core/main.rs
crates/proof-of-sql-sdk/src/client.rs

Currently there's a bit of redundancy in client input. The query_and_verify function accepts the table ref and query text in separate parameters. However, the table ref should always just be contained in the query text. This change makes it so the table-ref is parsed out of the query text, and technically is forward-compatible with multi-table queries.
- **feat: parse table refs out of query text**
- **docs: mention how to get help text for CLI in README.md**

feat: parse table refs out of query text

---

Cargo.lock
Cargo.toml
crates/proof-of-sql-sdk-local/Cargo.toml
crates/proof-of-sql-sdk-local/src/lib.rs
crates/proof-of-sql-sdk-local/src/prover_query.rs
crates/proof-of-sql-sdk-local/src/uppercase_accessor.rs
crates/proof-of-sql-sdk-local/src/verify.rs

It turns out, after we get a successful response from the prover, we still need the QueryCommitments to act as a MetadataAccessor and CommitmentAccessor. However, the issue still remains that the query/proof plan will not necessarily match the all-uppercase chain data that the query commitments was built from.
This change makes UppercaseAccessor implement more proof-of-sql accessor traits. It also just treats it with a higher level concern in general, giving it its own module with documentation and tests.
Yes.

feat: implement more Accessors for UppercaseAccessor

---

Cargo.lock
Cargo.toml
crates/proof-of-sql-sdk-local/src/verify.rs
crates/proof-of-sql-sdk-wasm/src/lib.rs
crates/proof-of-sql-sdk/src/client.rs

Latest version of `proof-of-sql` allows parameterized queries. We enable them in `proof-of-sql-sdk-local` but not the two downstream crates in this repo yet since we need to consider what the APIs should look like.

feat: bump `proof-of-sql` to `0.91.1`

---

Cargo.lock
crates/proof-of-sql-sdk-wasm/Cargo.toml
crates/proof-of-sql-sdk-wasm/src/lib.rs
examples/chainlink/source.js
examples/deno/query.js
examples/node/query.js

The return type of `verify_prover_response_dory`, (`OwnedTable`), is not working with `JsValue::from_serde`, because there is a dictionary key that is not a string. This handles that problem.
Returning a dictionary type rather than an `OwnedTable` type from `verify_prover_response_dory`.
Not really.

fix: return type of wasm verify_prover_response_dory

---

Cargo.lock
Cargo.toml
crates/proof-of-sql-sdk-local/Cargo.toml
crates/proof-of-sql-sdk-local/src/lib.rs
crates/proof-of-sql-sdk-local/src/prover_query.rs
crates/proof-of-sql-sdk-local/src/uppercase_accessor.rs
crates/proof-of-sql-sdk-local/src/verify.rs
crates/proof-of-sql-sdk-wasm/Cargo.toml
crates/proof-of-sql-sdk-wasm/src/lib.rs
crates/proof-of-sql-sdk/Cargo.toml
crates/proof-of-sql-sdk/examples/cli/args.rs
crates/proof-of-sql-sdk/src/client.rs
crates/proof-of-sql-sdk/src/lib.rs
node/src/index_tail.js

We want the sdk to be using the planner, not the parser
Removal of the parser in favor of the planner
There is no new functionality, only modification of existing functionality. The tests are probably lacking as is, so possibly not.

feat: rip out parser

---

node/src/index_tail.js

The way the logic is currently written, any http request that takes longer than 3 seconds will be aborted. This is not desirable, for obvious reasons.
Removal of the timeout
Kind of. There's examples that use this code.

fix: remove timeout from post http request

---

Cargo.lock
Cargo.toml

We need to upgrade proof of sql across the board for testing the new group by functionality in solidity.
Upgrade of proof of sql
Yes

feat!: upgrade proof of sql to 0.114.0

---

.cargo/config.toml
.github/workflows/lint-and-test.yml

It is annoying to copy and paste the default cargo fmt command.

feat: add shortcuts for default config for fmt

---

Cargo.lock
Cargo.toml
crates/proof-of-sql-sdk-local/src/commitment_scheme.rs
crates/proof-of-sql-sdk-local/src/lib.rs
crates/proof-of-sql-sdk-local/src/prover_query.rs

- add `CommitmentEvaluationProofId`
- make logic in `plan_prover_query_dory` generic and call it `plan_prover_query`. The original function `plan_prover_query_dory` doesn't have functionality changes. A new function, `plan_prover_query_hyperkzg`, is added.

feat: make `sxt-proof-of-sql-sdk-local` crate multi-commitment scheme and add support for hyperkzg

---

crates/proof-of-sql-sdk-local/src/commitment_scheme.rs
crates/proof-of-sql-sdk-local/src/lib.rs
crates/proof-of-sql-sdk-local/src/prover_query.rs

This fixes the NIT in #89. It is better to have our own SDK definition of `CommitmentScheme` and provide conversion to prover `CommitmentScheme` and chain `CommitmentScheme`.
- define `CommitmentScheme` for the SDK
- impl `From<CommitmentScheme>` for `prover::CommitmentScheme` and `commitment_scheme::CommitmentScheme`

feat: add `CommitmentScheme` and add conversions 

---

Cargo.lock
crates/proof-of-sql-sdk-local/Cargo.toml
crates/proof-of-sql-sdk-local/src/lib.rs
crates/proof-of-sql-sdk-local/src/proof_plan.rs
crates/proof-of-sql-sdk/Cargo.toml
crates/proof-of-sql-sdk/examples/produce-plan/args.rs
crates/proof-of-sql-sdk/examples/produce-plan/main.rs
crates/proof-of-sql-sdk/src/lib.rs
crates/proof-of-sql-sdk/src/plan.rs

In order to address https://internal.jira.makeinfinite.com/browse/PROOF-966, we want to be able to more easily generate a proof plan from our sdk.
New cli example for producing a proof plan.
No.

feat: proof plan cli command

---

Cargo.toml
crates/proof-of-sql-sdk-local/Cargo.toml
crates/proof-of-sql-sdk-local/src/commitment_scheme.rs
crates/proof-of-sql-sdk-local/src/lib.rs
crates/proof-of-sql-sdk-local/src/prover_query.rs
crates/proof-of-sql-sdk/Cargo.toml

HyperKZG is currently not WASM-compatible hence we need to put it behind a feature flag in the `sxt-proof-of-sql-sdk-local` crate and enable it in the `sxt-proof-of-sql-sdk` crate so that it will be available but not in `sxt-proof-of-sql-sdk-wasm`.

fix: add hyperkzg feature to local crate

---

crates/proof-of-sql-sdk-local/src/commitment_scheme.rs
crates/proof-of-sql-sdk-local/src/prover_query.rs
crates/proof-of-sql-sdk-local/src/verify.rs

Depends on #97.
For hyperkzg we need to use `EVMProofPlan`. Hence I added `CommitmentEvaluationProofId::AssociatedProofPlan` to allow this switch without a lot of duplicate code.

feat: add `CommitmentEvaluationProofId::AssociatedProofPlan` and switch hyperkzg to using `EVMProofPlan`

---

.cargo/config.toml
Cargo.toml
src/args.rs

We don't want "sxt" in the CLI name. Also rustflags do not belong to `Cargo.toml`. Technically this change is breaking since we attempt to change the CLI binary name.

fix!: remove "sxt" from cli name & move rustflags to `.cargo/config.toml`

---

Cargo.toml
src/base/commitment_scheme.rs
src/query_and_verify.rs

Debug for `OwnedTable` is not user-friendly. Hence we switch to Arrow to print our query results.

feat: use arrow pretty-print

---

Cargo.lock
Cargo.toml

chore: bump proof-of-sql to 0.118.0

---

Cargo.lock
Cargo.toml
src/base/prover_query.rs

Bump `proof-of-sql` to 0.121.0
Downgrade `sqlparser` to 0.44.0
Downgrade `datafusion` to 37.1.0
for consistency.

chore: bump `proof-of-sql` to 0.121.0

---

src/base/attestation.rs

The `create_attestation_message` code we have in SDK does not line up with [sxt-node](https://github.com/spaceandtimefdn/sxt-node/blob/626f83e7e7dffc1ec1d929adf2515054c35b31c5/sxt-core/src/attestation.rs#L287-L304). Hence we need to fix it.
This is technically a breaking change since `create_attestation_message` was and is public and its functionality is clearly changing for people who use the SDK lib.

fix!: fix `create_attestation_message` to line up with `sxt-node`

---

src/base/attestation.rs

Depends on #130.
Add comprehensive attestation verification functionality including:
- New error types for verification failures
- Attestation getter methods (signature, proposed_pub_key, state_root, block_number)
- verify_attestations function that validates signatures and Merkle proofs
- Comprehensive test coverage with real attestation data

feat: add `verify_attestation`

---

src/base/verifiable_commitment.rs

Add functionality to extract QueryCommitments from VerifiableCommitments:
- New extract_query_commitments_from_verifiable_commitments function
- Converts IndexMap of VerifiableCommitments to QueryCommitments
- Handles bincode deserialization of TableCommitment data
- Comprehensive test coverage with real commitment data

feat: add `extract_query_commitments_from_verifiable_commitments`

---

src/native/commitment.rs

Addressing a non-blocking review in #123 . Namely it is a good idea to rename `query_commitments` since there is already another one.

 fix: rename `native::commitment::query_commitments` to `query_verified_commitments`

---

Cargo.lock
Cargo.toml
src/base/mod.rs
src/base/zk_query_models.rs
src/native/mod.rs
src/native/zk_query_client.rs

We in fact need this merged earlier to unblock the last PR on attestation in SDK.

feat: add zk query API for proof plans

---

examples/count-ethereum-core/main.rs
src/base/zk_query_models.rs
src/native/client.rs
src/query_and_verify.rs

ZK Query API has a `network` param so we need to enable it before #143.

feat: add `network` to `SxTClient`
